on:
  push:
    paths:
      - '**.R'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      # - name: Install pandoc
      #   run: |
      #     brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Render graph files
        run: |
          R_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]graphs.R$'))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) source(f)' ${R_PATH[*]}

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build static graphs' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
