on:
  workflow_dispatch:
  push:
    paths:
      - '**.R'

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      # - name: Install pandoc
      #   run: |
      #     brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
          R -e 'install.packages(c("curl", "httr"))'
          R -e 'install.packages(c("remotes", "dplyr", "tidyr", "ggplot2", "ggridges", "roll", "scales", "forcats"))'
          R -e 'remotes::install_github("epiforecasts/covidregionaldata")'

      - name: Render graph files
        run: |
          GRAPH_PATH=("R/ridgeline_graphs.R")
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) source(f)' ${GRAPH_PATH[*]}

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add ${extra/.png}
          git commit -m 'Re-build static graphs' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
